### ISSUE TITLE
OneDrive "Files On Demand" support

### ISSUE THREAD

**Issue by TimNFL** [mgr32/PsISEProjectExplorer#80]
PSISEProjectExplorer doesn't seem to support OneDrive Folders when I enable the new "Files on Demand" feature. I keep all of my scripts in my OneDrive Folder for easy access and synchronization. When I enable the "Files on demand" feature I am unable access any of the files in that folder. Switching the workspace folder to another folder works as expected, but switching back to the OneDrive folder fails and shows 0 files.

**Comment by Seumpie** [comment]
Any update on this topic?

**Comment by mgr32** [comment]
Currently it is not supported as it would require implementing support of Reparse Points and possibly also ability not to index files contents (see #35) as, if I understand correctly, the files are not physically stored on disk, so not available for indexing.

Planned for 1.4.1, but not sure when it will happen. Contributions are welcome.

**Comment by imorrish** [comment]
VS Code had the same issue and it was fixed in underlying libuv functionality
https://github.com/libuv/libuv/commit/e5024c54a1d015607698849d69882174203f8205
if that helps.
I see ISE sticking around for on server administration (PsISEProjectExplorer is great on SharePoint servers) but most of us are probably moving over to VSCode for every day POSH work.

**Comment by arcanecode** [comment]
Just FYI, I turned off Files on Demand in OneDrive. Rebooted. Still doesn't work in OneDrive, although it works fine elsewhere. I have all the files persisted on my PC (always have). 

Pity as I love this add-in. At least it still works outside OneDrive.

**Comment by mgr32** [comment]
Released in 1.4.1 - please let me know if it works ok.

**Comment by arcanecode** [comment]
I just tested on three different machines. Search works, as does the index files mode. I can see files in OneDrive, whether I have them always saved or on demand.

**Comment by mgr32** [comment]
Great, thanks @arcanecode!
